version: '3.7'

services:
    gym-booking-service:
        container_name: gym-booking-service
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 8084:8084
        command: npm run start:dev
        networks:
            - webnet
        depends_on:
            - gym-booking-service-db
    gym-booking-service-db:
        container_name: gym-booking-service-db
        image: postgres:13.2
        networks:
            - webnet
        restart: always
        environment:
            POSTGRES_DB: 'gym-booking-service-db'
            POSTGRES_USER: 'booking'
            POSTGRES_PASSWORD: 'password'
            PGDATA: /data/postgres
        expose:
            - 5432
        ports:
            - 5432:5432
        volumes:
            - postgres:/data/postgres
networks:
    webnet:
volumes:
    postgres:
